version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    networks:
      - my-network
  frontend:
    build: ./frontend
    ports:
      - 8081:8081
    networks:
      - my-network

networks:
  my-network:
    driver: bridge